# -*- coding: utf-8 -*-
"""Baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOi2EDo6DABz033TIhzhYDH941MQeB73
"""

import numpy as np
import librosa
import soundfile as sf
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay
from sklearn.preprocessing import LabelEncoder

# Check if train_df and test_df exist, if not load from CSV
if 'train_df' not in globals():
    if os.path.exists('train.csv'):
        train_df = pd.read_csv('train.csv')
        print("Loaded train_df from train.csv")
        # Inserted code for modifying diagnosis labels in train_df
        if 'train_df' in globals():
            print("Modifying diagnosis labels in train_df for 3-class classification (ILD, Healthy, Other)...")
            train_df['diagnosis'] = train_df['diagnosis'].apply(lambda x: x if x in ['ILD', 'Healthy'] else 'Other')
            print("Train set new label distribution:")
            display(train_df['diagnosis'].value_counts(normalize=True))
    else:
        print("Warning: train.csv not found. Ensure data loading cell is run.")

if 'test_df' not in globals():
    if os.path.exists('test.csv'):
        test_df = pd.read_csv('test.csv')
        print("Loaded test_df from test.csv")
        # Inserted code for modifying diagnosis labels in test_df
        if 'test_df' in globals():
            print("Modifying diagnosis labels in test_df for 3-class classification (ILD, Healthy, Other)...")
            test_df['diagnosis'] = test_df['diagnosis'].apply(lambda x: x if x in ['ILD', 'Healthy'] else 'Other')
            print("Test set new label distribution:")
            display(test_df['diagnosis'].value_counts(normalize=True))
    else:
        print("Warning: test.csv not found.")

# Helper function for feature extraction (defined to ensure availability)
def extract_features(file_path):
    try:
        # load_audio is assumed to be available from the initial setup cell
        # If load_audio is not in the namespace, one would need to define it or use librosa.load
        if 'load_audio' in globals():
            wav, sr = load_audio(file_path)
        else:
            wav, sr = sf.read(file_path)
            if wav.ndim > 1: wav = np.mean(wav, axis=1)
            wav = wav.astype(np.float32)
            sr = sr # Keeping original SR if load_audio missing

        stft = np.abs(librosa.stft(wav))
        mfccs = np.mean(librosa.feature.mfcc(y=wav, sr=sr, n_mfcc=40), axis=1)
        chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sr), axis=1)
        contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sr), axis=1)
        tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(wav), sr=sr), axis=1)
        return np.hstack([mfccs, chroma, contrast, tonnetz])
    except Exception as e:
        return None

# Ensure lists are initialized
# Updated: explicitly clear lists before population
X_train_list = []
y_train_list = []
X_test_list = []
y_test_list = []

# Check and populate training data if missing or inconsistent
# Updated print statement
print("Populating training features with modified labels...")
if 'train_df' in globals():
    for _, row in train_df.iterrows():
        feat = extract_features(row['filepath'])
        if feat is not None:
            X_train_list.append(feat)
            y_train_list.append(row['diagnosis'])

# Check and populate testing data if missing or inconsistent
# Updated print statement
print("Populating testing features with modified labels...")
if 'test_df' in globals():
    for _, row in test_df.iterrows():
        feat = extract_features(row['filepath'])
        if feat is not None:
            X_test_list.append(feat)
            y_test_list.append(row['diagnosis'])

# Convert to numpy arrays
X_train = np.array(X_train_list)
X_test = np.array(X_test_list)

if len(X_train) > 0 and len(X_test) > 0:
    # Encode labels
    le = LabelEncoder()
    y_train = le.fit_transform(y_train_list)
    y_test = le.transform(y_test_list)

    # Initialize and train Random Forest Classifier
    rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
    rf_clf.fit(X_train, y_train)

    # Predict on test set
    y_pred = rf_clf.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy Score: {accuracy:.4f}")

    # Plot Confusion Matrix
    plt.figure(figsize=(10, 8))
    ConfusionMatrixDisplay.from_predictions(y_test, y_pred, display_labels=le.classes_, cmap=plt.cm.Blues)
    plt.title("Confusion Matrix (3-Class Classification)") # Updated title
    plt.show()
else:
    print("Insufficient data extracted to train model. Check file paths and data loading.")